---
name: Submodule Updates

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master, main]

jobs:
  build:
    name: Submodule update
    runs-on: docker
    env:
      PARENT_REPOSITORY: 'foxzi/tt_ee'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      PARENT_UPDATED_BRANCH: 'test-branch-for-pr'
      TEXT_PULL_REQUEST: 'Submodule updated time for renew'
      OWNER: 'foxzi'

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: foxzi/github-action-create-pr-parent-submodule@v1.1.2
        with:
          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          parent_updated_branch: ${{ env.PARENT_UPDATED_BRANCH }}
          text_pull_request: "${{ env.TEXT_PULL_REQUEST }}"
          owner: ${{ env.OWNER }}
